#+title: Emacs Configuration

#+property: header-args:emacs-lisp :tangle ./init.el
#+startup: content

* Optimizations

  Make startup faster by reducing the frequency of garbage collection

  #+begin_src emacs-lisp
  (setq gc-cons-threshold most-positive-fixnum ; 2^61 bytes
	gs-cons-percentage 0.6)
  #+end_src

  Reset garbage collection after startup

  #+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
	    (lambda ()
	      (setq gc-cons-threshold 16777216 ; 16 mb
		    gs-cons-percentage 0.1)))
  #+end_src

  Raise gc-cons-threshold while the minibuffer is active, so the GC doesn’t slow
  down expensive commands (or completion frameworks, like helm and ivy)

  #+begin_src emacs-lisp
  (defun rst/defer-garbage-collection-h ()
    (setq gc-cons-threshold most-positive-fixnum))

  (defun rst/restore-garbage-collection-h ()
    ;; Defer it so that commands launched immediately after will enjoy the
    ;; benefits.
    (run-at-time
     1 nil (lambda () (setq gc-cons-threshold 16777216))))

  (add-hook 'minibuffer-setup-hook #'rst/defer-garbage-collection-h)
  (add-hook 'minibuffer-exit-hook #'rst/restore-garbage-collection-h)
  #+end_src

  Emacs resizes the (GUI) frame when your newly set font is larger
  (or smaller) than the system default

  #+begin_src emacs-lisp
  (setq frame-inhibit-implied-resize t)
  #+end_src

* Package System Setup

  Initialize package

  #+begin_src emacs-lisp
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			   ("org" . "https://orgmode.org/elpa/")
			   ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  #+end_src

  Install =use-package= and configure it to always ensure packages

  #+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t
	use-package-verbose t)
  #+end_src

* General

  Merge system clipboard with emacs kill ring

  #+begin_src emacs-lisp
  (setq save-interprogram-paste-before-kill t)
  #+end_src

  Move backup and auto-save files to tmp

  #+begin_src emacs-lisp
  (setq backup-directory-alist
	`((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
	`((".*" ,temporary-file-directory t)))
  #+end_src

  Make ESC quit prompts

  #+begin_src emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
  #+end_src

  Add =/usr/local/bin= to emacs environment to access executables like =rg=
  Add =/Library/TeX/texbin= to emacs environment to access LaTeX executables
  Add =~/go/bin= to emacs environment to access go executables like =gopls=
  Add =/usr/local/go/bin= to emacs environment to access go executables like =go=

  #+begin_src emacs-lisp
  (setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin:/Library/TeX/texbin:~/go/bin:/usr/local/go/bin"))
  (setq exec-path (append exec-path '("/usr/local/bin" "/Library/TeX/texbin" "~/go/bin" "/usr/local/go/bin")))
  #+end_src

  Install undo tree

  #+begin_src emacs-lisp
  (use-package undo-tree
    :diminish (undo-tree-mode . "Ⓤ")
    :config
    (global-undo-tree-mode))
  #+end_src

  Install counsel, swiper and ivy. Setup global bindings.

  #+begin_src emacs-lisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
	   ("C-x b" . counsel-ibuffer)
	   ("C-x C-f" . counsel-find-file)))

  (use-package swiper
    :diminish)

  (use-package ivy-avy)
  (use-package ivy-hydra)

  (use-package ivy
    :diminish
    :bind (:map ivy-minibuffer-map
		("TAB" . ivy-alt-done)
		("C-l" . ivy-alt-done)
		("M-RET" . ivy-immediate-done)
		("C-h" . ivy-beginning-of-buffer)
		("C-j" . ivy-next-line)
		("C-k" . ivy-previous-line)
		("C-w" . evil-delete-backward-word)
		("C-a" . ivy-dispatching-done)
		("C-i" . ivy-avy)
		("C-e" . ivy-occur)
		:map ivy-switch-buffer-map
		("C-k" . ivy-previous-line)
		("C-l" . ivy-done)
		("C-d" . ivy-switch-buffer-kill)
		:map ivy-reverse-i-search-map
		("C-k" . ivy-previous-line)
		("C-d" . ivy-reverse-i-search-kill))
    :config
    (setq ivy-initial-inputs-alist nil
	  ivy-wrap t
	  ivy-re-builders-alist
	  '((t   . ivy--regex-ignore-order)))
    (ivy-mode 1))
  #+end_src

  Show some ivy/counsel buffers in popups

  #+begin_src emacs-lisp
  (use-package ivy-posframe
    :commands ivy-posframe-mode
    :diminish (ivy-posframe-mode . "ⒾⓅ")
    :config
    (setq ivy-posframe-display-functions-alist
	  '((swiper          . ivy-posframe-display-at-frame-top-center)
	    (counsel-M-x     . ivy-posframe-display-at-frame-top-center)
	    (t               . ivy-posframe-display-at-frame-top-center)))
    (setq ivy-posframe-width 100
	  ivy-posframe-min-width 100
	  ivy-posframe-height 10
	  ivy-posframe-min-height 10
	  ivy-posframe-border-width 20))
  #+end_src

  Install =which-key= and other helpful information packages.

  #+begin_src emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish
    :config
    (setq which-key-idle-delay 1)
    (setq which-key-allow-evil-operators t)
    (setq which-key-add-column-padding 4))

  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
  #+end_src

  Install evil and evil packages.

  #+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t
	  evil-want-keybinding nil
	  evil-want-C-u-scroll t
	  evil-want-C-i-jump t)
    :custom
    (evil-search-module 'evil-search)
    (evil-undo-system 'undo-tree)
    :config
    (evil-mode 1)

    ;; Unbind conflicting keys
    (define-key evil-ex-completion-map (kbd "C-k") nil)
    (define-key evil-insert-state-map (kbd "C-k") nil)

    (define-key evil-insert-state-map (kbd "C-e") 'evil-append-line)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line))

  (use-package evil-collection
    :after evil
    :config
    ;; disable company integration. It breaks stuff
    (setq evil-collection-mode-list (remove 'company evil-collection-mode-list))
    (evil-collection-init))

  (use-package evil-args
    :after evil
    :config
    (require 'evil-args)
    ;; bind evil-args text objects
    (define-key evil-inner-text-objects-map "a" 'evil-inner-arg)
    (define-key evil-outer-text-objects-map "a" 'evil-outer-arg))

  (use-package evil-exchange
    :after evil
    :config
    (require 'evil-exchange)
    (evil-exchange-cx-install))

  (use-package evil-indent-plus
    :after evil
    :config
    (define-key evil-inner-text-objects-map "i" 'evil-indent-plus-i-indent)
    (define-key evil-outer-text-objects-map "i" 'evil-indent-plus-a-indent)
    (define-key evil-inner-text-objects-map "I" 'evil-indent-plus-i-indent-up)
    (define-key evil-outer-text-objects-map "I" 'evil-indent-plus-a-indent-up)
    (define-key evil-inner-text-objects-map "J" 'evil-indent-plus-i-indent-up-down)
    (define-key evil-outer-text-objects-map "J" 'evil-indent-plus-a-indent-up-down))

  (use-package evil-matchit
    :after evil
    :config
    (global-evil-matchit-mode 1))

  (use-package evil-nerd-commenter
    :after evil)

  (use-package evil-surround
    :after evil
    :config
    (global-evil-surround-mode 1))

  (use-package evil-numbers
    :after evil
    :bind
    (:map evil-normal-state-map
	  ("C-a" . evil-numbers/inc-at-pt)))

  (use-package evil-snipe
    :after evil
    :config
    (setq evil-snipe-scope 'visible)
    ;; improve f command
    (evil-snipe-override-mode 1))
  #+end_src

  Workaround evil bindings not there before hitting =ESC=
  https://github.com/emacs-evil/evil/issues/301

  #+begin_src emacs-lisp
  (add-hook 'org-src-mode-hook 'evil-normalize-keymaps)
  #+end_src

  Enable auto-completion with =company=

  #+begin_src emacs-lisp
  (use-package company
    :commands company-mode
    :diminish (company-mode . "Ⓒ")
    :bind
    (:map company-active-map
	  ("C-j" . company-select-next)
	  ("C-k" . company-select-previous))
    :custom
    ((company-minimum-prefix-length 2)
     (company-idle-delay 0.2))
    :hook
    ((text-mode . company-mode)
     (prog-mode . company-mode))
    :config
    ;; Disable tab so it doesn't conflict with other expansions
    (define-key company-active-map (kbd "<tab>") nil)
    (define-key company-active-map (kbd "C-w") nil))
  #+end_src

  Add =yasnippet= support for all company backends
  Source: https://github.com/syl20bnr/spacemacs/pull/179

  #+begin_src emacs-lisp
  (defvar company-mode/enable-yas t
    "Enable yasnippet for all backends.")

  (defun company-mode/backend-with-yas (backend)
    (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
	backend
      (append (if (consp backend) backend (list backend))
	      '(:with company-yasnippet))))

  (with-eval-after-load 'company
    (setq company-backends (mapcar #'company-mode/backend-with-yas company-backends)))
  #+end_src

  Add a way to visualize projects structure with =treemacs=

  #+begin_src emacs-lisp
  (use-package treemacs
    :commands treemacs
    :config
    (setq treemacs-indentation 2))

  (use-package treemacs-evil
    :after treemacs evil)

  (use-package treemacs-all-the-icons
    :after treemacs
    :config
    (treemacs-load-theme "all-the-icons"))
  #+end_src

  Add a way to jump through code more efficiently with =avy=.
  Configure it display overlay chars before match.

  #+begin_src emacs-lisp
  (use-package avy
    :config
    (setq avy-background t
	  avy-style 'pre))
  #+end_src

  Delete trailing whitespaces on file save

  #+begin_src emacs-lisp
  (add-hook 'before-save-hook 'whitespace-cleanup)
  #+end_src

  Unbind right meta key

  #+begin_src emacs-lisp
  (setq ns-right-alternate-modifier 'none)
  #+end_src

  Enable all local variables. *WARNING* this is risky

  #+begin_src emacs-lisp
  (setq enable-local-variables :all)
  #+end_src

  Start an empty scratch buffer

  #+begin_src emacs-lisp
  (setq initial-scratch-message "")
  #+end_src

  Disable ls on dired if system type is =darwin=

  #+begin_src emacs-lisp
  (when (string= system-type "darwin")
    (setq dired-use-ls-dired nil))
  #+end_src

  Enable narrowing commands

  #+begin_src emacs-lisp
  (put 'narrow-to-defun  'disabled nil)
  (put 'narrow-to-page   'disabled nil)
  (put 'narrow-to-region 'disabled nil)
  #+end_src

  Install expand region

  #+begin_src emacs-lisp
  (use-package expand-region
    :commands er/expand-region)
  #+end_src

  Uniquify buffer names

  #+begin_src emacs-lisp
  (setq uniquify-buffer-name-style 'forward)
  #+end_src

** Dired

   Enable a way to filter files in dired

   #+begin_src emacs-lisp
   (use-package dired-narrow)
   #+end_src

   When there is two dired windows, copy and move commands will default to the
   other window directory.

   #+begin_src emacs-lisp
   (setq dired-dwim-target t)
   #+end_src

* UI
** General

   Disable startup message

   #+begin_src emacs-lisp
   (setq inhibit-startup-message t)
   #+end_src

   Disable visual scrollbar, toolbar, tooltips and menubar

   #+begin_src emacs-lisp
   (scroll-bar-mode -1)
   (tool-bar-mode -1)
   (tooltip-mode -1)
   (menu-bar-mode -1)
   #+end_src

   Widen fringe a little bit

   #+begin_src emacs-lisp
   (set-fringe-mode 5)
   #+end_src

   Use spaces instead of tabs

   #+begin_src emacs-lisp
   (setq indent-tabs-mode nil)
   #+end_src

   Show column number in mode line

   #+begin_src emacs-lisp
   (column-number-mode)
   #+end_src

   Increase line spacing

   #+begin_src emacs-lisp
   (setq-default line-spacing 0.3)
   #+end_src

   Show relative line numbers in =prog-mode=

   #+begin_src emacs-lisp
   (add-hook 'prog-mode-hook
	     (lambda ()
	       (display-line-numbers-mode t)
	       (setq display-line-numbers 'relative)))
   #+end_src

   Remove bottom emacs window margins (happens on Mac OS)

   #+begin_src emacs-lisp
   (setq frame-resize-pixelwise t)
   #+end_src

   Highlight trailing whitespaces everywhere but some modes

   #+begin_src emacs-lisp
   (dolist (hook '(text-mode-hook
		   prog-mode-hook))
     (add-hook hook
	       (lambda () (setq show-trailing-whitespace t))))
   #+end_src

   Remove title bar icon. Looks ugly

   #+begin_src emacs-lisp
   (setq ns-use-proxy-icon nil)
   #+end_src

   Highlight current line

   #+begin_src emacs-lisp
   (global-hl-line-mode 1)
   #+end_src

   Disable bell

   #+begin_src emacs-lisp
   (setq ring-bell-function 'ignore)
   #+end_src

   Render unicode characters correctly

   #+begin_src emacs-lisp
   (use-package unicode-fonts
     :config (unicode-fonts-setup))
   #+end_src

   Diminish minor modes in mode-line

   #+begin_src emacs-lisp
   (use-package diminish)
   #+end_src

** Colors

   Define evil mode colors

   #+begin_src emacs-lisp
   (setq evil-normal-color "DarkGoldenrod2"
	 evil-insert-color "chartreuse3"
	 evil-emacs-color "SkyBlue2"
	 evil-replace-color "chocolate"
	 evil-visual-color "gray"
	 evil-motion-color "plum3"
	 evil-iedit-color "firebrick1")
   #+end_src

   Define spaceline iedit face

   #+begin_src emacs-lisp
   (defface rst/spaceline-iedit-face
     `((t :foreground "black"
	  :background ,evil-iedit-color))
     "Face for spaceline iedit state")
   #+end_src

** Theme

   Don't dim modeline when window is inactive

   #+begin_src emacs-lisp
   (defun rst/do-nothing (&rest args) t)
   (advice-add 'powerline-selected-window-active :around 'rst/do-nothing)
   #+end_src

   Configure the mode line and set a theme

   #+begin_src emacs-lisp
   (use-package doom-themes)
   (doom-themes-treemacs-config)

   (use-package zerodark-theme)
   (use-package spacemacs-common
     :ensure spacemacs-theme)

   (use-package all-the-icons)

   (load-theme 'spacemacs-dark t)

   (use-package spaceline-config
     :ensure spaceline
     :config
     (setq powerline-default-separator "slant"
	   powerline-height 25)
     (set-face-attribute 'spaceline-evil-normal nil
			 :foreground "black"
			 :background evil-normal-color)
     (set-face-attribute 'spaceline-evil-replace nil
			 :foreground "black"
			 :background evil-replace-color)
     (set-face-attribute 'spaceline-evil-insert nil
			 :foreground "black"
			 :background evil-insert-color)
     (set-face-attribute 'spaceline-evil-visual nil
			 :foreground "black"
			 :background evil-visual-color)
     (set-face-attribute 'spaceline-evil-motion nil
			 :foreground "black"
			 :background evil-motion-color)
     (set-face-attribute 'spaceline-evil-emacs nil
			 :foreground "black"
			 :background evil-emacs-color))

   (spaceline-compile
     '(((persp-name
	 workspace-number
	 window-number)
	:separator " ⃒ "
	:fallback evil-state
	:face highlight-face
	:priority 100)
       (anzu :priority 95)
       auto-compile
       ((buffer-modified buffer-id remote-host)
	:priority 98)
       (major-mode :priority 79)
       (process :when active)
       ((flycheck-error flycheck-warning flycheck-info)
	:when active
	:priority 89)
       (minor-modes :when active
		    :priority 9)
       (mu4e-alert-segment :when active)
       (erc-track :when active)
       (version-control :when active
			:priority 78)
       (org-pomodoro :when active)
       (org-clock :when active)
       nyan-cat)

     '(projectile-root
       which-function
       (python-pyvenv :fallback python-pyenv)
       (purpose :priority 94)
       (battery :when active)
       (selection-info :priority 95)
       input-method
       (buffer-encoding-abbrev
	:priority 96)
       (buffer-position :priority 99)
       (hud :priority 99)))

   (setq spaceline-evil-state-faces
	 '((normal . spaceline-evil-normal)
	   (insert . spaceline-evil-insert)
	   (emacs . spaceline-evil-emacs)
	   (replace . spaceline-evil-replace)
	   (visual . spaceline-evil-visual)
	   (motion . spaceline-evil-motion)
	   (iedit . rst/spaceline-iedit-face)
	   (iedit-insert . rst/spaceline-iedit-face))
	 spaceline-highlight-face-func 'spaceline-highlight-face-evil-state
	 spaceline-minor-modes-separator "·")

   (setq-default mode-line-format '("%e" (:eval (spaceline-ml-main))))
   #+end_src

** Font

   Set default font

   #+begin_src emacs-lisp
   (set-face-attribute 'default nil :font "Source Code Pro" :height 130)
   #+end_src

   Disable python =and= and =or= ligatures

   #+begin_src emacs-lisp
   (setq python-prettify-symbols-alist '(("lambda" . 955)))
   #+end_src

   Enable Fira Code ligatures

   #+begin_src emacs-lisp
   (use-package fira-code-mode
     :diminish
     :custom (fira-code-mode-disabled-ligatures '("[]" "#{" "#(" "#_" "#_(" "x")) ;; List of ligatures to turn off
     :hook prog-mode)
   #+end_src

** Dashboard

   Install dashboard and configure its look

   #+begin_src emacs-lisp
   (use-package dashboard
     :config
     (dashboard-setup-startup-hook)
     (setq dashboard-center-content t)
     (setq dashboard-set-heading-icons t)
     (setq dashboard-set-file-icons t)
     (setq dashboard-banner-logo-title "Welcome rstcruzo!")
     (setq dashboard-items '((agenda . 3)
			     (recents . 3)
			     (projects . 3)
			     (bookmarks . 3)))
     (setq dashboard-set-init-info t)
     (setq dashboard-startup-banner "~/Pictures/Icons/emacs.png"))
   #+end_src

** Window

   Assign number to each window. Used to jump between windows.

   #+begin_src emacs-lisp
   (use-package winum
     :config
     (winum-mode)
     (winum--clear-mode-line))
   #+end_src

   Group winum bindings in which-key by creating a fake key to represent all ten
   keys and hiding other keys

   #+begin_src emacs-lisp
   (push '(("\\(.*\\) 1" . "winum-select-window-1") .
	   ("\\1 1..9" . "window 1..9"))
	 which-key-replacement-alist)

   (push '((nil . "winum-select-window-[2-9]") . t)
	 which-key-replacement-alist)
   #+end_src

   Allow window operations to be undone

   #+begin_src emacs-lisp
   (winner-mode 1)
   #+end_src

** Workspaces

   Use eyebrowse to manage workspaces

   #+begin_src emacs-lisp
   (use-package eyebrowse
     :config
     (eyebrowse-mode t)
     (setq eyebrowse-new-workspace t))
   #+end_src

** Tabs

   Install and configure centaur tabs

   #+begin_src emacs-lisp
   (use-package centaur-tabs
     :demand
     :config
     (setq centaur-tabs-set-icons t
	   centaur-tabs-gray-out-icons 'buffer
	   centaur-tabs-style "wave"
	   centaur-tabs-cycle-scope 'tabs
	   centaur-tabs-set-modified-marker t
	   centaur-tabs-modified-marker "☻")
     (centaur-tabs-headline-match)
     (centaur-tabs-group-by-projectile-project)
     (centaur-tabs-mode t)
     :bind
     (:map evil-normal-state-map
	   ("gt" . centaur-tabs-forward)
	   ("gT" . centaur-tabs-backward)))
   #+end_src

   Ignore some buffers and magit

   #+begin_src emacs-lisp
   (defun centaur-tabs-hide-tab (x)
     "Do no to show buffer X in tabs."
     (let ((name (format "%s" x)))
       (or
	;; Current window is not dedicated window.
	(window-dedicated-p (selected-window))

	;; Buffer name not match below blacklist.
	(string-prefix-p "*epc" name)
	(string-prefix-p "*helm" name)
	(string-prefix-p "*Helm" name)
	(string-prefix-p "*Compile-Log*" name)
	(string-prefix-p "*lsp" name)
	(string-prefix-p "*company" name)
	(string-prefix-p "*Flycheck" name)
	(string-prefix-p "*tramp" name)
	(string-prefix-p " *Mini" name)
	(string-prefix-p "*help" name)
	(string-prefix-p "*straight" name)
	(string-prefix-p " *temp" name)
	(string-prefix-p "*Help" name)
	(string-prefix-p "*mybuf" name)
	(string-prefix-p "magit" name)
	)))
   #+end_src

   When grouping projects, add eshell to the term group

   #+begin_src emacs-lisp
   (defun centaur-tabs-projectile-buffer-groups ()
     "Return the list of group names BUFFER belongs to."
     (if centaur-tabs-projectile-buffer-group-calc
	 (symbol-value 'centaur-tabs-projectile-buffer-group-calc)
       (set (make-local-variable 'centaur-tabs-projectile-buffer-group-calc)

	    (cond
	     ((or
	       (get-buffer-process (current-buffer))
	       (memq major-mode '(comint-mode compilation-mode))
	       (equal major-mode 'eshell-mode))
	      '("Term"))
	     ((string-equal "*" (substring (buffer-name) 0 1)) '("Misc"))
	     ((condition-case _err
		  (projectile-project-root)
		(error nil)) (list (projectile-project-name)))
	     ((memq major-mode '(emacs-lisp-mode python-mode emacs-lisp-mode c-mode
						 c++-mode javascript-mode js-mode
						 js2-mode makefile-mode
						 lua-mode vala-mode)) '("Coding"))
	     ((memq major-mode '(nxhtml-mode html-mode
					     mhtml-mode css-mode)) '("HTML"))
	     ((memq major-mode '(org-mode calendar-mode diary-mode)) '("Org"))
	     ((memq major-mode '(dired-mode)) '("Dir"))
	     (t '("Other"))))
       (symbol-value 'centaur-tabs-projectile-buffer-group-calc)))
   #+end_src

** Diminish some built-in minor modes

   Diminish =auto-revert-mode= and =el-doc-mode=

   #+begin_src emacs-lisp
   (use-package autorevert
     :ensure nil
     :config
     (diminish 'auto-revert-mode "ⒶⓇ"))

   (use-package eldoc
     :ensure nil
     :config
     (diminish 'eldoc-mode))
   #+end_src

** Popups

   Add ability to close some windows with just =C-g=

   #+begin_src emacs-lisp
   (use-package popwin
     :config
     (popwin-mode 1)
     (push '(TeX-output-mode :noselect t :tail t) popwin:special-display-config)
     (push "*scratch*" popwin:special-display-config))
   #+end_src

* Org Mode

  Basic configuration

  #+begin_src emacs-lisp
  (defvar rst/org-files-path "~/Dropbox/org/")

  (use-package org
    :diminish (org-src-mode . "ⓄⓈ")
    :config
    (setq org-agenda-start-with-log-mode t)
    (setq org-log-done 'time)
    (setq org-log-into-drawer t)
    (setq org-ellipsis " ↩")
    (setq org-agenda-files `(,rst/org-files-path)))
  #+end_src

  Configure a project org file

  #+begin_src emacs-lisp
  (defvar rst/org-projectile-filename nil
    "Org file for current projectile notes.")

  (defun rst/org-projectile-file ()
    "Return current project org file."
    (let ((project-name (projectile-project-name)))
      (if (not (string= project-name "-"))
	  (setq rst/org-projectile-filename
		(concat
		 (file-name-as-directory rst/org-files-path)
		 project-name ".org"))
	(message "Not in a project...")
	nil
	)
      )
    )

  (defun rst/open-org-projectile-file ()
    (interactive)
    (let ((org-file (rst/org-projectile-file)))
      (if org-file
	  (find-file org-file))))
  #+end_src

  Configure todo keywords. Add a few states

  #+begin_src emacs-lisp
  (setq org-todo-keywords
	'((sequence "TODO(t)" "|" "DONE(d!)")
	  (sequence "BLOCKED(b)" "|" "DELEGATED(D)" "CANCELLED(c)")))
  #+end_src

  Improve org heading bullets

  #+begin_src emacs-lisp
  (use-package org-bullets
    :after org
    :config
    (setq org-bullets-bullet-list
	  '("○" "☉" "◎" "◉" "○" "◌" "◎" "●" "◦" "◯" "⚪" "⚫" "⚬" "❍" "￮" "⊙" "⊚" "⊛" "∙" "∘"))
    :hook (org-mode . org-bullets-mode))
  #+end_src

  Change org headings size

  #+begin_src emacs-lisp
  (dolist (face '((org-level-1 . 1.3)
		  (org-level-2 . 1.2)
		  (org-level-3 . 1.1)
		  (org-level-4 . 1.05)
		  (org-level-5 . 1.1)
		  (org-level-6 . 1.1)
		  (org-level-7 . 1.1)
		  (org-level-8 . 1.1)))
    (set-face-attribute (car face) nil
			:font "Fira Code Retina"
			:weight 'regular
			:height (cdr face)))
  #+end_src

  Configure org title size and style

  #+begin_src emacs-lisp
  (set-face-attribute 'org-document-title nil
		      :underline t
		      :height 1.4)
  #+end_src

  Configure templates expansion

  #+begin_src emacs-lisp
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("mmd" . "src mermaid"))
  #+end_src

  Add padding to document

  #+begin_src emacs-lisp
  (defun org-mode-visual-fill ()
    (setq visual-fill-column-width 100
	  visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . org-mode-visual-fill))

  (setq org-edit-src-content-indentation 0)
  #+end_src

  Install =ob-mermaid= to render mermaid diagrams with org-babel.
  *NOTE*: Has to be loaded after mermaid-mode to override =org-babel-execute:mermaid=.

  #+begin_src emacs-lisp
  (use-package ob-mermaid
    :after mermaid-mode)
  #+end_src

  Display inline images automatically after executing source block

  #+begin_src emacs-lisp
  (defun org-display-images-after-execute ()
    "Redisplay inline images after executing source blocks with mermaid results."
    (let ((language (car (org-babel-get-src-block-info t))))
      (when (string= language "mermaid")
	(org-display-inline-images))))

  (add-hook 'org-babel-after-execute-hook #'org-display-images-after-execute)
  #+end_src

  Don't ask for confirmation when executing a source block

  #+begin_src emacs-lisp
  (setq org-confirm-babel-evaluate nil)
  #+end_src

  Add export backends

  #+begin_src emacs-lisp
  (setq org-export-backends '("ascii" "html" "icalendar" "latex" "odt" "md"))
  #+end_src

  Install better evil bindings in orgmode

  #+begin_src emacs-lisp
  (use-package evil-org
    :diminish
    :after org
    :config
    (add-hook 'org-mode-hook 'evil-org-mode)
    (add-hook 'evil-org-mode-hook
	      (lambda ()
		(evil-org-set-key-theme)))
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys))
  #+end_src

  Show fancier priorities symbols

  #+begin_src emacs-lisp
  (use-package org-fancy-priorities
    :diminish
    :ensure t
    :hook
    (org-mode . org-fancy-priorities-mode)
    :config
    (setq org-fancy-priorities-list '("😈" "😃" "💩")))
  #+end_src

  Use pomodoro technique for time management

  #+begin_src emacs-lisp
  (use-package org-pomodoro
    :after org)
  #+end_src

* Development

** Editing

   Install =evil-iedit-state=, a variant of multi-cursors for evil.

   #+begin_src emacs-lisp
   (use-package evil-iedit-state)
   #+end_src

   Install wgrep to edit files in a grep buffer.
   Used to do project-wide edits with ivy-occur.

   #+begin_src emacs-lisp
   (use-package wgrep)
   #+end_src

** Projectile

   Install projectile and search for projects in =~/Code=.
   We use ivy as completion system and install counsel for better integration.

   #+begin_src emacs-lisp
   (use-package projectile
     :diminish
     :config (projectile-mode)
     :custom ((projectile-completion-system 'ivy))
     :init
     (when (file-directory-p "~/Code")
       (setq projectile-project-search-path '("~/Code"))))

   ;; Install better ivy and projectile integration
   (use-package counsel-projectile
     :config (counsel-projectile-mode))

   (counsel-projectile-modify-action
    'counsel-projectile-switch-project-action
    '((default counsel-projectile-switch-project-action-dired)))

   (counsel-projectile-modify-action
    'counsel-projectile-find-file-action
    '((default counsel-projectile-find-file-action-other-window)))
   #+end_src

   Enable ivy rich after counsel projectile, they depend on this

   #+begin_src emacs-lisp
   (use-package all-the-icons-ivy-rich
     :init (all-the-icons-ivy-rich-mode 1))

   (use-package ivy-rich
     :init (ivy-rich-mode t))
   #+end_src

   Install treemacs and projectile integration

   #+begin_src emacs-lisp
   (use-package treemacs-projectile
     :after treemacs projectile)
   #+end_src

** Visual help

   Highlight pairs with different colors

   #+begin_src emacs-lisp
   (use-package rainbow-delimiters
     :defer t
     :hook
     (prog-mode . rainbow-delimiters-mode)
     (text-mode . rainbow-delimiters-mode))
   #+end_src

   Highlight enclosing parenthesis

   #+begin_src emacs-lisp
   (use-package highlight-parentheses
     :diminish (highlight-parentheses-mode . "ⒽⓅ")
     :ensure nil
     :config
     (set-face-attribute 'highlight-parentheses-highlight nil
			 :weight 'ultra-bold))

   (setq highlight-parentheses-colors
	 '("Springgreen3" "IndianRed1" "IndianRed3" "IndianRed4"))

   (add-hook 'prog-mode-hook 'highlight-parentheses-mode)
   #+end_src

   Automatically insert closing pairs and integrate it will evil.
   Also, highlight matching pair.

   #+begin_src emacs-lisp
   (use-package smartparens
     :diminish (smartparens-mode . "ⓈⓅ")
     :defer t
     :config
     (require 'smartparens-config)
     (set-face-attribute 'sp-show-pair-match-face nil
			 :foreground "#86dc2f"
			 :weight 'ultra-bold
			 :underline t)
     :hook
     (text-mode . show-smartparens-mode)
     (prog-mode . show-smartparens-mode)
     (text-mode . smartparens-mode)
     (prog-mode . smartparens-mode))

   (use-package evil-smartparens
     :defer t
     :config
     (add-hook 'emacs-lisp-mode-hook #'evil-smartparens-mode))
   #+end_src

   Highlight indent levels

   #+begin_src emacs-lisp
   (use-package highlight-indent-guides
     :config
     (setq highlight-indent-guides-method 'character
	   highlight-indent-guides-responsive 'top
	   highlight-indent-guides-auto-top-character-face-perc 20)
     :hook
     (prog-mode . highlight-indent-guides-mode))
   #+end_src

   Change cursor color depending on evil mode

   #+begin_src emacs-lisp
   (setq evil-normal-state-cursor `(,evil-normal-color box)
	 evil-motion-state-cursor `(,evil-motion-color box)
	 evil-visual-state-cursor `(,evil-visual-color (hbar . 2))
	 evil-insert-state-cursor `(,evil-insert-color (bar . 2))
	 evil-replace-state-cursor `(,evil-replace-color (hbar . 2))
	 evil-emacs-state-cursor `(,evil-emacs-color box)
	 evil-iedit-state-cursor `(,evil-iedit-color box)
	 evil-iedit-insert-state-cursor `(,evil-iedit-color (bar . 2)))
   #+end_src

** Version Control

   Install magit and integrate it with vim

   #+begin_src emacs-lisp
   (use-package magit
     :commands (magit-status magit-blame-addition))

   (use-package evil-magit
     :after magit)

   (use-package forge
     :commands (magit-status))
   #+end_src

   Enter Magit commit buffer in start mode

   #+begin_src emacs-lisp
   (add-hook 'git-commit-mode-hook 'evil-insert-state)
   #+end_src

   Visualize git hunks in the fringe. Make sure they are updated when
   we operate on magit.

   #+begin_src emacs-lisp
   (use-package diff-hl
     :config
     (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
     (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
     (global-diff-hl-mode)
     (diff-hl-flydiff-mode))
   #+end_src

   Integrate treemacs with magit

   #+begin_src emacs-lisp
   (use-package treemacs-magit
     :after treemacs magit)
   #+end_src

   Generate links to the remote file

   #+begin_src emacs-lisp
   (use-package git-link
     :commands git-link)
   #+end_src

** Terminal

   Install =vterm= and =shell-pop=. Configure it to use =zsh= and show
   at the bottom.

   #+begin_src emacs-lisp
   (use-package vterm
     :commands vterm
     :config
     (setq vterm-max-scrollback 10000))

   (use-package shell-pop
     :commands shell-pop
     :custom
     ((shell-pop-window-size 30)
      (shell-pop-window-position "bottom")
      (shell-pop-cleanup-buffer-at-process-exit t)
      (shell-pop-autocd-to-working-dir t)
      (shell-pop-term-shell "/usr/local/bin/zsh")
      (shell-pop-shell-type (quote ("eshell" "eshell-pop" (lambda nil (eshell)))))))
   #+end_src

   Hide modeline in shell pop ups.

   #+begin_src emacs-lisp
   (add-hook 'shell-pop-in-after-hook
	     (lambda () (setq mode-line-format nil)))
   #+end_src

   Configure eshell

   #+begin_src emacs-lisp
   (defun rst/configure-eshell ()
     ;; Save command history when commands are entered
     (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

     ;; Truncate buffer for performance
     (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

     (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-r") 'counsel-esh-history)

     (setq eshell-history-size 10000
	   eshell-buffer-maximum-lines 10000
	   eshell-hist-ignoredups t
	   eshell-scroll-to-bottom-on-input t))
   #+end_src

   Install eshell git prompt to show git info in eshell

   #+begin_src emacs-lisp
   (use-package eshell-git-prompt)

   (use-package eshell
     :ensure nil
     :hook (eshell-first-time-mode . rst/configure-eshell)
     :config
     (with-eval-after-load 'esh-opt
       (setq eshell-destroy-buffer-when-process-dies t)
       (setq eshell-visual-commands '("htop" "zsh" "vim")))
     (eshell-git-prompt-use-theme 'robbyrussell))
   #+end_src

** Snippets

   #+begin_src emacs-lisp
   (use-package yasnippet
     :diminish (yas-minor-mode . "Ⓨ")
     :config
     (yas-global-mode 1))

   (use-package yasnippet-snippets)
   #+end_src

** Languages

*** Checkers

    Configure flycheck and its fringe bitmap

    #+begin_src emacs-lisp
    (use-package flycheck
      :diminish (flycheck-mode . "Ⓕ")
      :custom
      (flycheck-python-flake8-executable "flake8")
      (flycheck-python-pylint-executable "pylint")
      :config

      (define-fringe-bitmap 'flycheck-fringe-bitmap-ball
	(vector #b00000000
		#b00000000
		#b00000000
		#b00000000
		#b00000000
		#b01100000
		#b11110000
		#b11110000
		#b11110000
		#b01100000
		#b00000000
		#b00000000
		#b00000000
		#b00000000
		#b00000000
		#b00000000))

      (flycheck-define-error-level 'error
	:severity 2
	:compilation-level 2
	:overlay-category 'flycheck-error-overlay
	:fringe-bitmap 'flycheck-fringe-bitmap-ball
	:fringe-face 'flycheck-fringe-error
	:error-list-face 'flycheck-error-list-error)

      (flycheck-define-error-level 'warning
	:severity 1
	:compilation-level 2
	:overlay-category 'flycheck-warning-overlay
	:fringe-bitmap 'flycheck-fringe-bitmap-ball
	:fringe-face 'flycheck-fringe-warning
	:error-list-face 'flycheck-error-list-warning)

      (flycheck-define-error-level 'info
	:severity 0
	:compilation-level 2
	:overlay-category 'flycheck-info-overlay
	:fringe-bitmap 'flycheck-fringe-bitmap-ball
	:fringe-face 'flycheck-fringe-info
	:error-list-face 'flycheck-error-list-info))
    #+end_src

    Show flycheck information in a popups

    #+begin_src emacs-lisp
    (use-package flycheck-popup-tip
      :after flycheck
      :custom
      (flycheck-popup-tip-error-prefix "")
      :hook (flycheck-mode . flycheck-popup-tip-mode))
    #+end_src

*** Language Servers

    Install =lsp-mode=, configure a prefix and integrate with =which-key=.

    #+begin_src emacs-lisp
    (defun lsp-mode-setup ()
      (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
      (lsp-headerline-breadcrumb-mode))

    (use-package lsp-mode
      :diminish (lsp-mode . "Ⓛ")
      :commands (lsp lsp-deferred)
      :hook (lsp-mode . lsp-mode-setup)
      :init
      (setq lsp-keymap-prefix "C-c l")
      :config
      (lsp-enable-which-key-integration t))

    (use-package lsp-ui
      :after lsp
      :hook
      (lsp-mode . lsp-ui-mode))

    (use-package lsp-treemacs
      :after lsp)

    (use-package lsp-ivy
      :after lsp)
    #+end_src

*** Python

    Install sphinx docs support

    #+begin_src emacs-lisp
    (use-package sphinx-doc
      :commands sphinx-doc-mode
      :config
      :hook (python-mode . (lambda ()
			     (sphinx-doc-mode t))))
    #+end_src

    Enable =lsp-deferred= mode for python

    #+begin_src emacs-lisp
    (use-package lsp-python-ms
      :after lsp
      :ensure t
      :init (setq lsp-python-ms-auto-install-server t)
      :hook (python-mode . (lambda ()
			     (require 'lsp-python-ms)
			     (lsp))))  ; or lsp-deferred
    #+end_src

    Enable =flycheck= for python

    #+begin_src emacs-lisp
    (add-hook 'python-mode-hook 'flycheck-mode)
    #+end_src

*** Go

    Install =go-mode=

    #+begin_src emacs-lisp
    (use-package go-mode
      :commands go-mode)
    #+end_src

    Enable =lsp-deferred= mode for Go

    #+begin_src emacs-lisp
    (add-hook 'go-mode-hook
	      (lambda () (lsp-deferred)))
    #+end_src

    Set tab width to 4

    #+begin_src emacs-lisp
    (add-hook 'go-mode-hook
	      (lambda ()
		(setq indent-tabs-mode nil)
		(setq go-tab-width 4)
		(setq tab-width 4)))
    #+end_src

*** Javascript

    Set indent width to 2

    #+begin_src emacs-lisp
    (setq js-indent-level 2)
    #+end_src

*** Docker

    #+begin_src emacs-lisp
    (use-package dockerfile-mode
      :commands dockerfile-mode
      :config
      (add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode)))
    #+end_src

*** YAML

    #+begin_src emacs-lisp
    (use-package yaml-mode
      :commands yaml-mode
      :config
      (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode)))
    #+end_src

*** Kubernetes

    Manage kubernetes resources from emacs

    #+begin_src emacs-lisp
    (use-package kubernetes
      :commands (kubernetes-overview))

    (use-package kubernetes-evil
      :after kubernetes)
    #+end_src

* Writing

** General

   Highlight characters over 80

   #+begin_src emacs-lisp
   (use-package whitespace
     :diminish
     :commands whitespace-mode)

   (setq whitespace-line-column 80)
   (setq whitespace-style '(face lines-tail trailing))

   (add-hook 'prog-mode-hook 'whitespace-mode)
   (add-hook 'text-mode-hook 'whitespace-mode)
   #+end_src

   Flyspell correct word with ivy

   #+begin_src emacs-lisp
   (use-package flyspell
     :commands flyspell-mode
     :ensure nil
     :diminish (flyspell-mode . "ⓕ"))

   (use-package flyspell-correct
     :after flyspell)

   (use-package flyspell-correct-ivy
     :after flyspell-correct)
   #+end_src

** LaTeX

   Install AucTeX and simplify =TeX-font= bindings

   #+begin_src emacs-lisp
   (use-package tex-mode
     :ensure auctex
     :custom
     (LaTeX-font-list
      '((?a ""              ""  "\\mathcal{"    "}")
	(?b "\\textbf{"     "}" "\\mathbf{"     "}")
	(?c "\\textsc{"     "}")
	(?e "\\emph{"       "}")
	(?f "\\textsf{"     "}" "\\mathsf{"     "}")
	(?i "\\textit{"     "}" "\\mathit{"     "}")
	(?l "\\textulc{"    "}")
	(?m "\\textmd{"     "}")
	(?n "\\textnormal{" "}" "\\mathnormal{" "}")
	(?r "\\textrm{"     "}" "\\mathrm{"     "}")
	(?s "\\textsl{"     "}" "\\mathbb{"     "}")
	(?t "\\texttt{"     "}" "\\mathtt{"     "}")
	(?u "\\textup{"     "}")
	(?w "\\textsw{"     "}")
	(?d "" "" t))))
   #+end_src

   Automatically wrap long lines while writing

   #+begin_src emacs-lisp
   (add-hook 'LaTeX-mode-hook
	     (lambda () (auto-fill-mode)))
   (diminish 'auto-fill-function "ⓐⓕ")
   #+end_src

   Enable spell checking and show compilation buffer

   #+begin_src emacs-lisp
   (add-hook 'LaTeX-mode-hook
	     (lambda () (flyspell-mode 1)))

   (setq TeX-show-compilation t)
   #+end_src

   Define variable to store main TeX files. This file is used for compilation

   #+begin_src emacs-lisp
   (defvar TeX-main-filename "main"
     "TeX main file to use for compilation.")

   (defun TeX-main-file (&optional extension &rest r)
     "Retrieve TeX main filename to use with AUCTeX."
     (interactive)
     (if (eq extension t)
	 (setq extension TeX-default-extension))
     (if (null extension)
	 TeX-main-filename
       (format "%s.%s" TeX-main-filename extension)))
   #+end_src

   Add =@online= entry to bibtex

   #+begin_src emacs-lisp
   (use-package bibtex
     :commands bibtex-mode
     :ensure nil
     :config
     (setq bibtex-dialect 'biblatex))
   #+end_src

** Translate

   Install google translate and its dependency popup.
   Configure languages too.

   #+begin_src emacs-lisp
   (use-package popup)
   (use-package google-translate
     :commands google-translate-smooth-translate
     :config
     (setq google-translate-translation-directions-alist
	   '(("en" . "es") ("es". "en"))))

   (use-package google-translate-default-ui
     :after google-translate
     :ensure nil)
   #+end_src

** Diagrams

   Install mermaid mode

   #+begin_src emacs-lisp
   (use-package mermaid-mode
     :commands mermaid-mode)
   #+end_src

* Networking

  Add capabilities to add ssh-key to agent.

  #+begin_src emacs-lisp
  (defvar rst/ssh-default-key "~/.ssh/id_rsa"
    "My default SSH key.")

  (defun rst/ssh-add (&optional arg)
    "Add the default ssh-key if it's not present.
  With a universal argument, prompt to specify which key."
    (interactive "P")
    (when (or arg
	      (not (rst/ssh-agent-has-keys-p)))
      (rst/ssh-add-in-emacs
       (if (not arg)
	   rst/ssh-default-key
	 (read-file-name
	  "Add key: \n" "~/.ssh" nil 't nil
	  (lambda (x)
	    (not (or (string-suffix-p ".pub" x)
		     (string= "known_hosts" x)))))))))

  (defun rst/ssh-agent-has-keys-p ()
    "Return t if the ssh-agent has a key."
    (when
	(= 0 (call-process "ssh-add" nil nil nil "-l"))
      t))

  (defun rst/ssh-add-in-emacs (key-file)
    "Run ssh-add to add a key to the running SSH agent."
    (let ((process-connection-type t)
	  process)
      (unwind-protect
	  (progn
	    (setq process
		  (start-process
		   "ssh-add" nil "ssh-add"
		   (expand-file-name key-file)))
	    (set-process-filter
	     process 'rst/ssh-add-process-filter)
	    (while (accept-process-output process)))
	(if (eq (process-status process) 'run)
	    (kill-process process)))))

  (defun rst/ssh-add-process-filter (process string)
    "Process filter to enter passphrase when needed."
    (save-match-data
      (if (string-match ":\\s *\\'" string)
	  (process-send-string process
			       (concat
				(read-passwd string)
				"\n"))
	(message "ssh-add: %s" string))))
  #+end_src

* Custom functions

  Install hydra

  #+begin_src emacs-lisp
  (use-package hydra)
  #+end_src

  Define hydra function to scale text

  #+begin_src emacs-lisp
  (defhydra hydra-text-scale (:timeout 4)
    "Scale text"
    ("k" text-scale-increase "bigger")
    ("j" text-scale-decrease "smaller")
    ("q" nil "quit" :exit t))
  #+end_src

  Define hydra function to merge conflicts

  #+begin_src emacs-lisp
  (defhydra hydra-merge-conflicts ()
    "Merge conflicts"
    ("n" smerge-next "next conflict")
    ("p" smerge-prev "previous conflict")
    ("u" smerge-keep-upper "keep upper")
    ("l" smerge-keep-lower "keep lower")
    ("a" smerge-keep-all "keep all")
    ("q" nil "quit" :exit t))
  #+end_src

  Define custom counsel projectile search functions to better handle default
  inputs. This is used for =SPC /= and =SPC *= bindings.

  #+begin_src emacs-lisp
  (defun counsel-projectile-rg-with-input (&optional input)
    "Custom counsel projectile rg to receive input as argument."
    (interactive)
    (counsel-rg input
		(projectile-project-root)
		nil
		(projectile-prepend-project-name
		 (concat (car (if (listp counsel-rg-base-command)
				  counsel-rg-base-command
				(split-string counsel-rg-base-command)))
			 ": "))))

  (defun counsel-projectile-rg-thing-at-point ()
    "Custom counsel projectile rg to pass thing at point as input."
    (interactive)
    (let ((thing (ivy-thing-at-point)))
      (when (use-region-p)
	(deactivate-mark))
      (counsel-projectile-rg-with-input thing)))
  #+end_src

  Define way to quickly switch to last buffer

  #+begin_src emacs-lisp
  (defun switch-to-previous-buffer ()
    "Switch to previously open buffer.
  Repeated invocations toggle between the two most recently open buffers."
    (interactive)
    (switch-to-buffer (other-buffer (current-buffer) 1)))
  #+end_src

  Define way to add current project to treemacs

  #+begin_src emacs-lisp
  (defun projectile-add-to-treemacs ()
    "Add current project to treemacs workspace."
    (interactive)
    (treemacs-add-project-to-workspace (projectile-project-root)))
  #+end_src

  Define a way to split line smartly and enter a new line

  #+begin_src emacs-lisp
  (defun rst/split-and-new-line ()
    "Split a quoted string or s-expresion and insert a new line with
  auto-indent"
    (interactive)
    (sp-split-sexp 1)
    (sp-newline))
  #+end_src

* Keybindings

  #+begin_src emacs-lisp
  (use-package general
    :config

    (general-create-definer bind-leader-key
      :states '(normal insert motion visual emacs)
      :keymaps 'override
      :prefix "SPC"
      :global-prefix "C-SPC")

    (general-create-definer bind-mode-key
      :states '(normal insert motion visual emacs)
      :keymaps 'override
      :prefix ","
      :global-prefix "M-m")

    (general-create-definer bind-insert-mode
      :states '(insert))

    (general-create-definer bind-g-normal-mode
      :states '(normal)
      :prefix "g")

    (general-create-definer bind-op-square-brackets
      :states '(normal)
      :prefix "[")

    (general-create-definer bind-cl-square-brackets
      :states '(normal)
      :prefix "]")

    (bind-op-square-brackets
     "h" '(diff-hl-previous-hunk :which-key "git previous hunk"))

    (bind-cl-square-brackets
     "h" '(diff-hl-next-hunk :which-key "git next hunk"))

    (bind-leader-key
      :infix "q"
      "q" '(save-buffers-kill-terminal :which-key "quit"))

    (bind-leader-key
      "0" '(treemacs-select-window :which-key "window 0 - treemacs")
      "1" 'winum-select-window-1
      "2" 'winum-select-window-2
      "3" 'winum-select-window-3
      "4" 'winum-select-window-4
      "5" 'winum-select-window-5
      "6" 'winum-select-window-6
      "7" 'winum-select-window-7
      "8" 'winum-select-window-8
      "9" 'winum-select-window-9)

    (bind-insert-mode
      "C-c s" '(flyspell-auto-correct-word :which-key "auto-correct word"))

    (bind-g-normal-mode
      "c" '(evilnc-comment-operator :which-key "evilnc-comment-operator"))

    ;; Global binds or shortcuts
    (bind-leader-key
      "SPC" '(save-buffer :which-key "save buffer")

      "c" '(counsel-M-x :which-key "M-x")

      "/" '(counsel-projectile-rg-with-input :which-key "search project")
      "*" '(counsel-projectile-rg-thing-at-point :which-key "search project thing at point")

      "'" '(shell-pop :which-key "shell pop")

      "<tab>" '(switch-to-previous-buffer :which-key "switch to last buffer")

      "." '(projectile-find-file :which-key "find project file")
      "," '(counsel-switch-buffer :which-key "switch buffer")

      ":" '(eval-expression :which-key "eval expression")
      ";" '(ivy-resume :which-key "ivy resume")

      "v" '(er/expand-region :which-key "expand region")
      "u" '(universal-argument :which-key "universal argument"))

    (bind-leader-key
      :infix "f"
      "" '(:ignore t :which-key "files")
      "s" '(save-buffer :which-key "save file")
      "f" '(counsel-find-file :which-key "find file")
      "e" '((lambda () (interactive)
	      (find-file "~/.emacs.d/config.org"))
	    :which-key "find config file")
      "o" '((lambda () (interactive)
	      (counsel-find-file rst/org-files-path))
	    :which-key "find org file"))

    (bind-leader-key
      :infix "b"
      "" '(:ignore t :which-key "buffers")
      "b" '(counsel-switch-buffer :which-key "switch buffer")
      "k" '(kill-buffer :which-key "kill a buffer")
      "K" '(kill-current-buffer :which-key "kill current buffer")
      "s" '((lambda () (interactive)
	      (switch-to-buffer "*scratch*")) :which-key "switch to scratch")
      "S" '((lambda () (interactive)
	      (popwin:display-buffer "*scratch*")) :which-key "switch to popup scratch")
      "i" '(ibuffer :which-key "ibuffer")
      "R" '(revert-buffer :which-key "revert buffer"))

    (bind-leader-key
      :infix "t"
      "" '(:ignore t :which-key "toggles/text")

      ;; Text
      "t" '(google-translate-smooth-translate :which-key "google translate")
      "s" '(hydra-text-scale/body :which-key "scale text")

      "T" '(counsel-load-theme :which-key "choose theme")

      ;; Toggles
      "R" '(ivy-rich-mode :which-key "toggle ivy rich mode")
      "p" '(ivy-posframe-mode :which-key "toggle ivy posframe mode")

      "c" '(centaur-tabs-mode :which-key "toggle centaur tabs")

      "i" '(org-toggle-inline-images :which-key "toggle org inline images"))

    (bind-leader-key
      :infix "p"
      "" '(:ignore t :which-key "projects")
      "s" '(counsel-projectile-rg :which-key "search project")
      "v" '(projectile-edit-dir-locals :which-key "edit project dir locals")
      "d" '(projectile-dired :which-key "project dired")
      "p" '(projectile-switch-project :which-key "switch project")
      "f" '(projectile-find-file :which-key "find project file")
      "b" '(counsel-projectile-switch-to-buffer :which-key "switch to project buffer")
      "T" '(projectile-add-to-treemacs :which-key "add current project to treemacs")
      "n" '(rst/open-org-projectile-file :which-key "open project org file"))

    (bind-leader-key
      :infix "g"
      "" '(:ignore t :which-key "git")
      "g" '(magit-status :which-key "git status")
      "c" '(hydra-merge-conflicts/body :which-key "merge conflicts")
      "b" '(magit-blame-addition :which-key "blame")

      "s" '(diff-hl-diff-goto-hunk :which-key "show current hunk diff")
      "r" '(diff-hl-revert-hunk :which-key "revert current hunk")
      "n" '(diff-hl-next-hunk :which-key "next hunk")
      "p" '(diff-hl-previous-hunk :which-key "previous hunk")

      "l" '(git-link :which-key "git link"))

    (bind-leader-key
      :infix "s"
      "" '(:ignore t :which-key "search/spelling")
      "s" '(swiper :which-key "swiper")
      "S" '(swiper-thing-at-point :which-key "swiper thing at point")
      "c" '(evil-ex-nohighlight :which-key "clear highlight")

      "d" '(ispell-change-dictionary :which-key "change dictionary")
      "w" '(flyspell-auto-correct-word :which-key "auto-correct word")
      "W" '(flyspell-correct-at-point :which-key "correct word"))

    (bind-leader-key
      :infix "h"
      "" '(:ignore t :which-key "help")
      "v" '(describe-variable :which-key "describe variable")
      "f" '(describe-function :which-key "describe function")
      "F" '(counsel-describe-face :which-key "describe face")
      "k" '(describe-key :which-key "describe key")
      "m" '(describe-mode :which-key "describe mode"))

    (bind-leader-key
      :infix "l"
      "" '(:ignore t :which-key "lisp")
      "e" '(eval-last-sexp :which-key "eval last sexp")
      "p" '(check-parens :which-key "check parens"))

    (bind-leader-key
      :infix "o"
      "" '(:ignore t :which-key "org")
      "a" '(org-agenda :which-key "org agenda")
      "s" '(org-schedule :which-key "org schedule")
      "d" '(org-deadline :which-key "org deadline")
      "t" '(org-todo :which-key "org todo")
      "e" '(org-edit-src-code :which-key "org edit code")
      "r" '(org-babel-execute-src-block :which-key "org execute code")
      "i" '(org-display-inline-images :which-key "org display inline images"))

    (bind-leader-key
      :infix "w"
      "" '(:ignore t :which-key "windows/workspaces")
      "j" '(evil-window-down :which-key "move to window below")
      "k" '(evil-window-up :which-key "move to window above")
      "h" '(evil-window-left :which-key "move to window on the left")
      "l" '(evil-window-right :which-key "move to window on the right")

      "J" '(windmove-swap-states-down :which-key "move to window below")
      "K" '(windmove-swap-states-up :which-key "move to window above")
      "H" '(windmove-swap-states-left :which-key "move to window on the left")
      "L" '(windmove-swap-states-right :which-key "move to window on the right")

      "d" '(evil-window-delete :which-key "delete window")
      "s" '(evil-window-split :which-key "horizontal split")
      "v" '(evil-window-vsplit :which-key "vertical split")
      "m" '(delete-other-windows :which-key "maximize window")

      "w" '(eyebrowse-last-window-config :which-key "last workspace")
      "W" '(eyebrowse-switch-to-window-config :which-key "switch workspace")
      "n" '(eyebrowse-next-window-config :which-key "next workspace")
      "p" '(eyebrowse-prev-window-config :which-key "previous workspace")
      "r" '(eyebrowse-rename-window-config :which-key "rename workspace")
      "c" '(eyebrowse-close-window-config :which-key "close workspace")

      "u" '(winner-undo :which-key "winner undo")
      "U" '(winner-redo :which-key "winner redo")

      "M" '(popwin:messages :which-key "popup messages buffer"))

    (bind-mode-key
      :keymaps 'org-mode-map
      "," '(org-babel-tangle :which-key "org babel tangle")
      "t" '(org-todo :which-key "org todo")
      "c" '(:ignore t :which-key "clock")
      "ci" '(org-clock-in :which-key "org clock in")
      "co" '(org-clock-out :which-key "org clock out")
      "e" '(org-edit-src-code :which-key "org edit source")
      "s" '(org-schedule :which-key "org schedule")
      "d" '(org-deadline :which-key "org deadline")
      "r" '(org-babel-execute-src-block :which-key "org execute code")
      "i" '(org-display-inline-images :which-key "org display inline images"))

    (bind-mode-key
      :keymaps 'LaTeX-mode-map
      "e" '(LaTeX-environment :which-key "environment")
      "s" '(LaTeX-section :which-key "section")
      "i" '(LaTeX-insert-item :which-key "insert item")

      "C" '(TeX-command-master :which-key "compile")
      "c" '((lambda () (interactive) (TeX-command "LaTeX" 'TeX-main-file))
	    :which-key "compile LaTeX")
      "b" '((lambda () (interactive) (TeX-command "BibTeX" 'TeX-main-file))
	    :which-key "compile BibTeX")

      "f" '(TeX-font :which-key "font")
      "M" '(LaTeX-math-mode :which-key "math mode")
      "m" '(:ignore t :which-key "math")
      "mf" '(LaTeX-math-frac :which-key "fraction"))

    (bind-mode-key
      :keymaps 'bibtex-mode-map
      "e" '(bibtex-entry :which-key "bibtex entry")
      "t" '(bibtex-remove-OPT-or-ALT :which-key "bibtex remove OPT or ALT"))

    (bind-mode-key
      :keymaps 'org-src-mode-map
      "," '(org-edit-src-exit :which-key "org source exit")
      "s" '(org-edit-src-save :which-key "org source save")
      "e" '(org-edit-src-exit :which-key "org source exit")
      "a" '(org-edit-src-abort :which-key "org source abort")
      "k" '(org-edit-src-abort :which-key "org source abort")
      "q" '(org-edit-src-abort :which-key "org source abort"))

    (bind-mode-key
      :keymaps 'dired-mode-map
      "f" '(dired-narrow :which-key "dired narrow"))

    (bind-mode-key
      :keymaps 'git-commit-mode-map
      "," '(with-editor-finish :which-key "finish")
      "k" '(with-editor-cancel :which-key "cancel"))

    (bind-mode-key
      :keymaps 'python-mode-map
      "d" '(sphinx-doc :which-key "generate sphinx doc"))

    (bind-leader-key
      :infix "a"
      "" '(:ignore t :which-key "applications")
      "d" '(dired :which-key "dired")
      "t" '(treemacs :which-key "treemacs")
      "v" '(vterm :which-key "vterm")
      "e" '(eshell :which-key "eshell")
      "s" '(shell :which-key "shell")
      "i" '(ielm :which-key "ielm"))

    (bind-leader-key
      :infix "e"
      "" '(:ignore t :which-key "edit/errors")
      "e" '(evil-iedit-state/iedit-mode :which-key "iedit mode"))

    (bind-leader-key
      :infix "j"
      "" '(:ignore t :which-key "jump/split")
      "j" '(avy-goto-char-2 :which-key "jump to char 2")
      "w" '(avy-goto-word-1 :which-key "jump to word")
      "r" '(avy-resume :which-key "resume jump")
      "h" '(avy-org-goto-heading-timer :which-key "jump to org heading")
      "n" '(avy-next :which-key "jump to next candidate")
      "p" '(avy-prev :which-key "jump to previous candidate")

      "i" '(counsel-imenu :which-key "imenu")

      "c" '(avy-copy-region :which-key "jump, copy and paste")
      "m" '(avy-move-region :which-key "jump, cut and paste")

      "C" '(avy-copy-line :which-key "jump, copy and paste line")
      "M" '(avy-move-line :which-key "jump, cut and paste line")

      ;; split
      "S" '(sp-split-sexp :which-key "split sexp")
      "s" '(rst/split-and-new-line :which-key "split sexp and new line"))

    (bind-leader-key
      :infix "n"
      "" '(:ignore t :which-key "narrowing")
      "w" '(widen :which-key "widen")
      "r" '(narrow-to-region :which-key "narrow to region")
      "f" '(narrow-to-defun :which-key "narrow to defun"))

    (bind-leader-key
      :infix "i"
      "" '(:ignore t :which-key "insert")
      "c" '(counsel-yank-pop :which-key "insert from clipboard")
      "u" '(counsel-unicode-char :which-key "unicode char"))

    (bind-leader-key
      :infix "P"
      "" '(:ignore t :which-key "popups")
      "m" '(popwin:messages :which-key "popup messages")
      "s" '((lambda () (interactive)
	      (popwin:display-buffer "*scratch*")) :which-key "popup scratch")
      "l" '(popwin:popup-last-buffer :which-key "last popup"))
    )
  #+end_src

* Configuration Debugging

  Install bug-hunter

  #+begin_src emacs-lisp
  (use-package bug-hunter)
  #+end_src

* Post-init

  Workaround to centaur tabs and flyspell bug. Probably a race condition (?)
  When flyspell mode is enabled in a mode hook, the first file with that mode we
  open is not added to its project tab group. Looks related to initializing
  ispell, doing in at startup fixes the issue.

  #+begin_src emacs-lisp
  (ispell-set-spellchecker-params)
  (ispell-init-process)
  #+end_src

* Startup Time Analysis

  |-------+-------------------------------------------------------------------|
  | Time  | Action                                                            |
  |-------+-------------------------------------------------------------------|
  | 2.5s  | -                                                                 |
  | 2.24s | Use :commands to lazy load some packages                          |
  | 2.12s | Garbage collection optimizations                                  |
  | 2.4s  | Inhibiting window resizing on startup. I feel it faster though... |
  |-------+-------------------------------------------------------------------|

* Pending Configuration
** TODO [#C] Check use package and general integration
** TODO [#C] org wild notifier to show OS notifications
** TODO [#C] Check datetree
** TODO [#C] org capture templates (tables, datetrees, ...)
** TODO [#B] org habits
** DONE [#C] Why do I need to hit Escape in Org source mode to access "," bindings?
   CLOSED: [2020-11-04 Wed 23:10]
   :LOGBOOK:
   - State "DONE"       from "TODO"       [2020-11-04 Wed 23:10]
   :END:
** DONE Fix whitespace highlight on mini buffer
   CLOSED: [2020-10-24 Sat 13:42]
   :LOGBOOK:
   - State "DONE"       from "TODO"       [2020-10-24 Sat 13:42]
   :END:
** DONE Why when I press C-j and there is only one match in company box, new line is inserted
   CLOSED: [2020-10-24 Sat 23:51]
   :LOGBOOK:
   - State "DONE"       from "TODO"       [2020-10-24 Sat 23:51]
   :END:

   This was caused by evil collection. I disabled it and binded the keys in company mode
   manually.
** TODO [#B] Clean up go environment paths. HOME?
